### PR TITLE
Testnet 4 support

### PR DESCRIPTION
**Pull request by yoss22**
I've started updating the code to work with the latest versions of grin. It's nowhere near finished, but please let me know if you have any initial comments!

### CODE REVIEW

**Comment by dblokhin** [comment]
Great job! There is a lot of new/changed consensus rules. Do you have a documented list of them or something that approve it to related original grin-network?

**Comment by dblokhin** [comment]
There are a lot of changes. I need more time to check this code.

**Comment by yoss22** [comment]
I don't have a list of changed consensus rules - these commits are mostly just trying to replicate the functionality that was changed in the original grin codebase. Like you mentioned in the readme, the consensus rules and protocol (and even the POW) are still changing quite frequently.

Sorry that this PR is so large.

**Comment by yoss22** [comment]
Also it's not quite ready yet. I've been trying to validate blocks on testnet4 and the POW validation fails so I still need to look into that.

**Comment by yoss22** [comment]
I changed the import paths to make it build with the "go build" tool. With the previous import paths I had a lot of errors trying to resolve the packages. Unless I'm doing something totally wrong?

**Comment by dblokhin** [comment]
I dont know. It was buildable through native golang tools. May be GOPATH was incorrect. I'll check it.
Feel free to contribute! :+1:

**Pull request merged**
